ARG TAG=latest
FROM ubuntu:${TAG}

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing \
    && apt-get install -y wget bzip2 ca-certificates curl git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG MINICONDA3_VERSION=4.7.12.1
ARG MINICONDA3_MD5SUM=81c773ff87af5cfac79ab862942ab6b3

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA3_VERSION}-Linux-x86_64.sh -O ~/miniconda.sh \
    && cd ~ \
#     && echo "${MINICONDA3_MD5SUM} miniconda.sh" | md5sum -c \
    && /bin/bash ~/miniconda.sh -b -p /opt/conda \
    && rm ~/miniconda.sh \
    && /opt/conda/bin/conda clean -tipsy \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
    && echo "conda activate base" >> ~/.bashrc

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini

ENTRYPOINT [ "/usr/bin/tini", "--" ]

CMD [ "/bin/bash" ]

LABEL org.opencontainers.image.title="Miniconda 3" \
    org.opencontainers.image.description="Miniconda 3 on Ubuntu Linux in Docker" \ 
    org.opencontainers.image.url="https://github.com/carljohanrehn/quantlib-docker" \ 
    org.opencontainers.image.source="https://github.com/carljohanrehn/quantlib-docker" \
    org.opencontainers.image.version="${MINICONDA3_VERSION}"
