ARG TAG=latest

FROM carljohanrehn/quantlib-dev:${TAG} AS builder

ARG QUANTLIB_SWIG_VERSION=1.17
ENV QUANTLIB_SWIG_VERSION ${QUANTLIB_SWIG_VERSION}

COPY QuantLib-SWIG-${QUANTLIB_SWIG_VERSION} QuantLib-SWIG-${QUANTLIB_SWIG_VERSION}

RUN cd QuantLib-SWIG-${QUANTLIB_SWIG_VERSION}/Python \
    && CXXFLAGS='-g0 -O3' python setup.py bdist_wheel


FROM carljohanrehn/miniconda3:${TAG}

COPY --from=builder /usr/lib/libQuantLib.la /usr/lib/
COPY --from=builder /usr/lib/libQuantLib.so.0.0.0 /usr/lib/

RUN cd /usr/lib && ln -s libQuantLib.so.0.0.0 libQuantLib.so.0
RUN cd /usr/lib && ln -s libQuantLib.so.0.0.0 libQuantLib.so
RUN ldconfig

ARG QUANTLIB_SWIG_VERSION=1.17

COPY --from=builder /QuantLib-SWIG-${QUANTLIB_SWIG_VERSION}/Python/dist/QuantLib*.whl /tmp/

RUN pip install /tmp/QuantLib*.whl

CMD [ "/bin/bash" ]

LABEL org.opencontainers.image.title="QuantLib Miniconda 3" \
    org.opencontainers.image.description="QuantLib Miniconda 3 on Ubuntu Linux in Docker" \ 
    org.opencontainers.image.url="https://github.com/carljohanrehn/quantlib-docker" \ 
    org.opencontainers.image.source="https://github.com/carljohanrehn/quantlib-docker" \
    org.opencontainers.image.version="${QUANTLIB_SWIG_VERSION}"
