ARG TAG=latest

FROM carljohanrehn/boost:${TAG}

ARG QUANTLIB_VERSION=1.17
ENV QUANTLIB_VERSION ${QUANTLIB_VERSION}

COPY QuantLib-${QUANTLIB_VERSION} QuantLib-${QUANTLIB_VERSION} 
   
RUN cd QuantLib-${QUANTLIB_VERSION} \
    && ./configure --prefix=/usr --disable-static CXXFLAGS=-O3 \
    && make -j 4 && make check && make install \
    && cd .. && rm -rf QuantLib-${QUANTLIB_VERSION} && ldconfig

CMD [ "/bin/bash" ]

LABEL org.opencontainers.image.title="QuantLib" \
    org.opencontainers.image.description="QuantLib on Ubuntu Linux in Docker" \ 
    org.opencontainers.image.url="https://github.com/carljohanrehn/quantlib-docker" \ 
    org.opencontainers.image.source="https://github.com/carljohanrehn/quantlib-docker" \
    org.opencontainers.image.version="${QUANTLIB_VERSION}"
