ARG TAG=latest

FROM carljohanrehn/pytorch-quantlib-miniconda3-dev:${TAG}

EXPOSE 8888

RUN mkdir /home/notebooks
VOLUME /home/notebooks

COPY notebooks/*.ipynb /notebooks/

CMD jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=8888 --notebook-dir=/home/notebooks

LABEL org.opencontainers.image.title="QuantLib" \
    org.opencontainers.image.description="Jupyter Notebook with PyTorch and QuantLib on Ubuntu Linux in Docker" \ 
    org.opencontainers.image.url="https://github.com/carljohanrehn/docker-quantlib" \ 
    org.opencontainers.image.source="https://github.com/carljohanrehn/docker-quantlib" \
    org.opencontainers.image.version="${QUANTLIB_VERSION}"



